version: '3.8'

services:
  database:
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    depends_on:
      - database

volumes:
  postgres-data:
